version: '3.8'

services:
  mysqldb:
    image: mariadb:10.5.8
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    restart: always
    environment:
      - MYSQL_DATABASE=social
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3308:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - PMA_HOST=mysql
        - MYSQL_USER=root
      ports:
        - 8080:80